basePath: /
definitions:
  types.Product_PATCH_Body:
    type: object
  types.Product_POST_Body:
    type: object
  types.Response:
    type: object
host: localhost:3000
info:
  contact: {}
  description: API template
  title: Template-Go Microservice
  version: "1.0"
paths:
  /product:
    delete:
      description: This endpoint is used to delete product
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/types.Response'
        "403":
          description: Unauthorized, check HTTP Authorization header
      summary: Delete Product
      tags:
      - Product
    get:
      description: This endpoint is used to...
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/types.Response'
        "403":
          description: Unauthorized, check HTTP Authorization header
      summary: Get Product
      tags:
      - Product
    patch:
      description: this endpoint is used for...
      parameters:
      - description: Provide product details in the request body
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.Product_PATCH_Body'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/types.Response'
        "403":
          description: Unauthorized, check HTTP Authorization header
      summary: Patch Product
      tags:
      - Product
    post:
      description: this endpoint is used for...
      parameters:
      - description: Provide product details in the request body
        in: body
        name: product
        required: true
        schema:
          $ref: '#/definitions/types.Product_POST_Body'
      produces:
      - application/json
      responses:
        "200":
          description: Ok
          schema:
            $ref: '#/definitions/types.Response'
        "403":
          description: Unauthorized, check HTTP Authorization header
      summary: Post Product
      tags:
      - Product
swagger: "2.0"
